# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  RunTestsAndMerge:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r Azure\ Functions/requirements.txt
        pip install pytest
      shell: bash

    - name: Run Tests
      run: pytest Azure\ Functions/tests/
      shell: bash

    - name: Merge to Master
      if: startsWith(github.ref, 'refs/pull/') && github.event_name == 'push'
      run: |
        git checkout master
        git pull origin master
        git merge --no-ff --no-commit $GITHUB_REF
        git commit -m "Merge PR #$GITHUB_REF"
        git push
      shell: bash
