# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r Azure\ Functions/requirements.txt
    pip install pytest
    pytest Azure\ Functions/tests/
  displayName: 'Run Tests'
